_wandb:
    value:
        cli_version: 0.23.1
        e:
            pgf76v97i8p27to2yf3z91b7ok5h7dxu:
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "1081101176832"
                        used: "61521391616"
                email: jkorr@berkeley.edu
                executable: /mnt/c/Users/jkorr/Downloads/185HW/hw2/.venv/bin/python
                git:
                    commit: 18c1b3e6dbde09115c724cf952fa1c71df249bd9
                    remote: https://github.com/jkorrr/185HW.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-7ff9bb46-bd71-9bd3-65a2-0d3715e9d16f
                host: LAPTOP-EOU4JPHI
                memory:
                    total: "8009224192"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: <stdin>
                python: CPython 3.10.12
                root: /mnt/c/Users/jkorr/Downloads/185HW/hw2
                startedAt: "2026-02-23T18:51:49.197994Z"
                writerId: pgf76v97i8p27to2yf3z91b7ok5h7dxu
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
            "4": 3.10.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
